### ISSUE TITLE
Create a process to allow CE staff to submit updated schema information, without involving LT staff

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#289]
Currently when an update is necessary for the CTDL schema, the process is to:
- CE staff updates the Production section (https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/tree/master/Production_Schema) of the Schema Validation repo
- Notify LT staff of the update, and to which environments the change should be promoted

Would it be possible to develop a process where a CE staff person could submit an updated schema, and the appropriate environments would be updated?

Part of the process would be validation. I recall that sometimes Alex would identify an issue with the schema. Was this a manual step, or does an internal process do some validation. 
@jkitchensSIUC @siuc-nate

**Comment by excelsior** [comment]
An API for creating or updating schemas would be easy to implement. All the problems found with the recently promoted schemas were the result of a manual review. And some of those were caught well after the schemas were put to use. The only thing we verify automatically (and implicitly) is the format of a schema (i.e. an invalid JSON payload won't be persisted). I believe we can at least make sure that the uploaded payload meets the expected structure.

**Comment by siuc-nate** [comment]
@mparsons-ce @excelsior What is the status of this?

**Comment by excelsior** [comment]
I’m going to check whether schemas are actually used first. Apparently, they’re not needed for indexing purposes. And my understanding is that validation is always skipped when resources are published.

@mparsons-ce Do you know any other use cases?

**Comment by siuc-nate** [comment]
@excelsior will implement an updated process for this.

**Comment by excelsior** [comment]
@cwd-mparsons @siuc-nate This feature is available on sandbox. All of the API methods described below require authentication.

### The API for updating a community's config:

```
POST /metadata/{community_name}/config

{
  "description": "E.g. moar types added",
  "payload": "Updated config"
}
```

### To check what the current config looks like:

```
GET /metadata/{community_name}/config
```

This will fall back to the default config (the one we have in the repo) if nothing had been submitted before.

### Also, you can view the history of the changes:

```
GET /metadata/{community_name}/config/changes
```

Each changeset consists of the previous version and the diff between it and the next version.

### TODO

1. The payload isn't validated currently, it only needs to be well-formated JSON. Perhaps, we could come up with a JSON schema spec describing the config to avoid invalid values from being submitted.
2. If a config change affects any of the existing documents, the FTS index shoud be rebuilt. You can do that by running the Reindex All job from the C66 dashboard, but in the future, it'd be nice to detect such changes and partially rebuild the index automatically.
3. I plan to add an API for rolling back certain changes and probably reifying arbitrary versions from the past.

**Comment by mparsons-ce** [comment]
Currently I get a 401 on 
https://sandbox.credentialengineregistry.org/metadata/ce-registry/config

**Comment by mparsons-ce** [comment]
Alex
I noticed in the config file from github , there is the property: id_prefix:

![image](https://user-images.githubusercontent.com/58825866/106928373-ba547b80-66d8-11eb-9246-d2b74adbe84d.png)

Once I start using the API, will the latter be set for the current environment, or left as is (so handled internally)?
For example:
	"id_prefix": "http://**sandbox**.credentialengineregistry.org/resources/",

**Comment by excelsior** [comment]
@mparsons-ce It will stay as is. This is how it works right now, the prefixes are identical on all of the environments.

**Comment by excelsior** [comment]
@mparsons-ce 

I implemented an endpoint for publishing JSON schemas:

```
POST /schemas/{community_name}/{schema_name}

{
  <JSON schema definition>
}
```

The endpoint requires authentication, of course.

Also, there is a PUT endpoint with the same path which allows to update existing schemas the old way (i.e., by submitting a signed envelope), it doesn't support publishing new schemas, though. Let me know if you still need that enpoint or it shoud be removed.

On a semi-related note: are namesakes from different communities supposed to be identical? It's true for the majority of the schemas, but in came to my notice that the credential one differs a lot across CER and Navy:

1. https://github.com/learningtapestry/CredentialRegistry/blob/master/fixtures/schemas/ce_registry/credential.json
2. https://github.com/learningtapestry/CredentialRegistry/blob/master/fixtures/schemas/navy/credential.json 

Is that correct?

**Comment by mparsons-ce** [comment]
@excelsior That is strange. Yes, they should be the same.

**Comment by mparsons-ce** [comment]
@excelsior 
To update a config, you state:
```
POST /metadata/{community_name}/config
{
  "description": "E.g. moar types added",
  "payload": "Updated config"
}
```

Is payload a string or an object? I would have thought it was a object. Or do I have to serialize the JSON structure ( update: in retrospect this makes sense as that is how other publishing occurs).
I used the GET endpoint to get the current config, and added a new type of ceterms:Organization. I then did a POST to:
https://sandbox.credentialengineregistry.org/metadata/ce-registry/config

![image](https://user-images.githubusercontent.com/58825866/119893925-97f1a280-bf01-11eb-8b87-c8ddcdd47a64.png)

I get a valid response of 200 but no messages. The response is just the input JSON, so I don't know if the request was actually successful. If successful, are the updates applied immediately? I  

The JSON I used can be viewed here:
https://gist.github.com/mparsons-ce/d38e7767a262d0181ef4d9f2a86fcfc2

**Comment by mparsons-ce** [comment]
@excelsior 
I then tried the following:
- read config from a file
- add to the request object (description and payload)
-  serialize the object
- call endpoint
- **get: {"errors":["payload is invalid"]}**

```
string ce_registryConfigFile = "C:\\Users\\mparsons-ce\\Documents\\GitHub\\CredentialRegistry\\fixtures\\configs\\ce_registry.json";

var configFile = System.IO.File.ReadAllText( ce_registryConfigFile );
var request = new ConfigRequest()
{
	description = "Add ceterms:Organization",
	payload = configFile
};
var payload = JsonConvert.SerializeObject( request );
```
	
The following is the config file that was input to this process:
https://gist.github.com/mparsons-ce/ef3c406beaf6b9e7219c25f412733855

**Comment by mparsons-ce** [comment]
@excelsior 
Next I tried just getting the current config file, leave it unchanged and then calling the POST endpoint.
I still get invalid payload message. 
NOTE: I am going to upload the change to github as we need this implemented tomorrow (21-05-28).

**Comment by excelsior** [comment]
@mparsons-ce

1. A payload is expected to be a JSON object, so no serialization is required.
2. The endpoint returns the updated config if the update was successful, so yes, the output is supposed to match the input.
3. The changes do get applied immediately.

**Comment by mparsons-ce** [comment]
@excelsior @edgarf 
I successfully updated staging and production with the addition of ceterms:Organization.
Documentation 
Some time ago the following document was started for content  related to registry configuration.
https://docs.google.com/document/d/1mQRZVzXHaZaCYzJLEvASP9uIPsTQthvYlRCp-_CrRLs/edit#

I have been adding 'suggestions' to the document including the topic related to this issue. 
Could someone accept the suggestions or make updates as needed, thanks.

**Comment by mparsons-ce** [comment]
Completed
