### ISSUE TITLE
Ability to delete a registered publishing organization

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#307]
This is regarding organizations that are added to the registry as publishers.

In general, if an organization is being removed from the accounts system, etc, we will want to remove them as publishers from the registry. We would be responsible for ensuring they don't have published resources, or we could transfer ownership. 
Another scenario: 
- an organization is added to the accounts site and registered as a publisher in CR
- The organization gets deleted, and then re added. 
- The old registry public key (which was stored with the organization) has been lost, and an attempt to add again to the CR results in a duplicate index error on the CTID

**Comment by excelsior** [comment]
@mparsons-ce This feature is available for testing on sandbox. API: 

```
DELETE /metadata/organizations/{organization_id}
```

Available to admins only. The Swagger docs have been updated, too.

Also, an organization belongs to a publisher, but a publisher doesn't get deleted even if it's only remaining organization is removed.

**Comment by jeannekitchens** [comment]
@mparsons-ce waht's the status?

**Comment by mparsons-ce** [comment]
@excelsior 

Using
https://sandbox.credentialengineregistry.org/metadata/organizations
The org 'My competency org' exists.
![image](https://user-images.githubusercontent.com/58825866/89690859-23e00280-d8cd-11ea-81bd-a02022d454e1.png)

I tried calling the Delete endpoint:
https://sandbox.credentialengineregistry.org/metadata/organizations/a16e7b19-b6d3-4e6d-a240-b078c4977c22

I get a 404 error. 
![image](https://user-images.githubusercontent.com/58825866/89691162-db751480-d8cd-11ea-9531-cd4aa5cfe551.png)

**Comment by jeannekitchens** [comment]
@mparsons-ce deletes are not actually deleted.  Is this a delete or a purge?  Is this data that should not be in the Registry because it never should have been published?  This has been lingering as open since February.

**Comment by excelsior** [comment]
@mparsons-ce Turned out this functionality wasn't available on sandbox, I fixed that. Could you please try again?

**Comment by mparsons-ce** [comment]
@jeannekitchens In order for an organization to publish to the registry, a key is needed. When an organization gets approved in the accounts system for publishing, a registry endpoint is called to register the organization (in the CR). At that time the public/private key pair is created.  The public key is returned and stored in the account system. If the organization is to be removed or unapproved, we want to **remove** the registered organization from the credential registry. While it would be difficult for a previously approved and now not approved org to publish because of other checks, for consistency, we want to be able remove an organization from the list of organizations approved in the registry.

**Comment by jeannekitchens** [comment]
@mparsons-ce understood...and this has been an issue since February so what's the status?

**Comment by mparsons-ce** [comment]
@excelsior @edgarf 
I tried this again and still get a 404. 
The swagger docs still don't show a delete endpoint for metadata/organizations
https://sandbox.credentialengineregistry.org/swagger/index.html
![image](https://user-images.githubusercontent.com/58825866/97609855-204aac00-19e2-11eb-9c22-c44dc836ff4f.png)

**Comment by excelsior** [comment]
@mparsons-ce I redeployed this feature to sandbox, please give it one more try.

**Comment by mparsons-ce** [comment]
This does seem to work now. 
There was a case where I tried to delete an organization and got a message that the organization still owned documents in the registry, but I couldn't find any. CTID: **ce-6b62f237-3354-4e2c-b96d-3db5c10e91e3**
The following doesn't exist:
https://sandbox.credentialengineregistry.org/ce-registry/envelopes/**ce-6b62f237-3354-4e2c-b96d-3db5c10e91e3**


A useful addition would being able to query for documents owned by an organization.

**Comment by siuc-nate** [comment]
@excelsior will create an internal/administrative API endpoint to enable @mparsons-ce to get the data needed to test the above problem.

**Comment by mparsons-ce** [comment]
Next step: The registry will create an API endpoint to list documents owned by an organization.

**Comment by mparsons-ce** [comment]
This has been verified, please promote the code to staging and production.
